apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-github-actions
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.dora-on-deployed: dora-collector # changed this
spec:
  project: default

  source:
    repoURL: https://github.com/phoenix0xff/GitOps.git
    targetRevision: HEAD
    path: manifest
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true