apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:6d65305fcdd360e2ed7e1c514e712a014f369809
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /nonexistent-health # purposly wrong to trigger failure
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
