apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  annotations:
    dora.dev/source-commit: 0767c7feea3179edb679f6ee21c18e073ba0a049
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        org.opencontainers.image.revision: 0767c7feea3179edb679f6ee21c18e073ba0a049
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:0767c7feea3179edb679f6ee21c18e073ba0a049
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
