apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:823713b504a5da68bb1a66711d6e642802a27dff
          ports:
            - containerPort: 3000
