apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        sim-readiness-run: "20251027192246"
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:37445bb5715b95074f2164655d833c70b5764d1a
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /nonexistent-health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
