apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  annotations:
    dora.dev/source-commit: 5992e83f1f721353727d0dc553f46b3b9c74800e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        org.opencontainers.image.revision: 5992e83f1f721353727d0dc553f46b3b9c74800e
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:5992e83f1f721353727d0dc553f46b3b9c74800e
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
