apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  annotations:
    dora.dev/source-commit: 720b8d7b191ba32262bc9cdc83eec9fa4fc2e110
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        org.opencontainers.image.revision: 720b8d7b191ba32262bc9cdc83eec9fa4fc2e110
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:720b8d7b191ba32262bc9cdc83eec9fa4fc2e110
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
