apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  annotations:
    appCommit: b0f31946e5a6772a929417a1cad217a133105a4f
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:b0f31946e5a6772a929417a1cad217a133105a4f
          ports:
            - containerPort: 3000
