apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  annotations:
    appCommit: 56cb130b294c03bdc292577b75b54c8c6ae316d2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:56cb130b294c03bdc292577b75b54c8c6ae316d2
          ports:
            - containerPort: 3000
