apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        sim-readiness-run: "20251029233504"
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:76dec1de2eaa39bb4109474e44b82f4646eb4bc1
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /nonexistent-health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
