apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: ens19kav/my-app:57546ee69224b3a8593f27904d9063d3a314b406
        ports:
        - containerPort: 3000
