apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  annotations:
    dora.dev/source-commit: f2a65ad97637c2578730de0540316b08101ad4de
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        org.opencontainers.image.revision: f2a65ad97637c2578730de0540316b08101ad4de
        sim-crashloop-run: "20251101120300"
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:f2a65ad97637c2578730de0540316b08101ad4de
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          command:
            - /bin/sh
            - -c
          args:
            - echo Simulated CrashLoop; exit 1
