apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        sim-fault-run: "20251026112759"
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:53e333db9756dd1402efe9da0bd69f7dff2114cc
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /nonexistent-health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
