apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        sim-crashloop-run: "20251027133817"
    spec:
      containers:
        - name: node-app
          image: ens19kav/my-app:2f61a49ad249cd3995a4713a7b30a0b3849ede19
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          command:
            - /bin/sh
            - -c
          args:
            - echo Simulated CrashLoop; exit 1
