apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: ens19kav/my-app:b322cfc60206d42eebfb76e904476a6658b8f01b
        ports:
        - containerPort: 3000
